sudo chmod u+x
bash prereqs.sh
source ~/.profile
source ~/.bashrc
bash installgo.sh
source ~/.profile
source ~/.bashrc
bash installdocker.sh
source ~/.profile
source ~/.bashrc
bash fabric-setup.sh
source ~/.profile
source ~/.bashrc
bash caserver-setup.sh
source ~/.profile
source ~/.bashrc
bash jq.sh
source ~/.profile
source ~/.bashrc
bash dev-env.sh
source ~/.profile
source ~/.bashrc
